@startuml

class ServiceChannelHolder {
    -Map<String, channel> holder;
    +void init();
    +List<Channel> lookup(String serviceName);
    +void add(Channel channel);
    +void remove(Channel channel);
}

interface LoadBalance {
    selectChannel(Map<String,Object> params);
}

class LoadBalanceBasedOnWeight

LoadBalance <|-- LoadBalanceBasedOnWeight
@enduml