@startuml
ServerBootstrap -> SocketAddress: bind
ServerBootstrap -> NioServerSocketChannel: new
ServerBootstrap -> NioServerSocketChannel: init
ServerBootstrap -> ChannelHandler: childHandler
ServerBootstrap -> ChannelPipeline: addLast(handler)
@enduml