@startuml
Starter -> Starter: 获取总的配置
Starter -> Starter: ServiceLoader加载所有扩展的模块
Starter -> Starter: 对于总的配置中的每个模块
loop
    Starter -> Starter: 获取模块的配置
    Starter -> Starter: 用模块中的配置覆盖总的配置

end loop

@enduml